### ISSUE TITLE
error while doing save as

### ISSUE THREAD

**Issue by iamtimbulus** [tzunghaor/inkscape-eps-export#15]
Traceback (most recent call last):
  File "/home/adytia/.config/inkscape/extensions/aieps_output.py", line 1186, in <module>
    print(converter.convert())
  File "/home/adytia/.config/inkscape/extensions/aieps_output.py", line 1160, in convert
    self.walkElem(self.root)
  File "/home/adytia/.config/inkscape/extensions/aieps_output.py", line 901, in walkElem
    self.walkElem(child)
  File "/home/adytia/.config/inkscape/extensions/aieps_output.py", line 901, in walkElem
    self.walkElem(child)
  File "/home/adytia/.config/inkscape/extensions/aieps_output.py", line 901, in walkElem
    self.walkElem(child)
  [Previous line repeated 2 more times]
  File "/home/adytia/.config/inkscape/extensions/aieps_output.py", line 884, in walkElem
    self.elemStop(elem)
  File "/home/adytia/.config/inkscape/extensions/aieps_output.py", line 733, in elemStop
    offsetString = elem.get('offset').strip()
AttributeError: 'NoneType' object has no attribute 'strip'

**Comment by tzunghaor** [comment]
I hope it is fixed in version 1.0.9
If you still have errors, then please attach an SVG file that causes it.
